//
//  EFIconFontStrawberryIcon.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation
#if canImport(EFIconFontCore)
import EFIconFontCore
#endif

public extension EFIconFont {

    static let strawberryIcon = EFIconFontStrawberryIcon.self
}

extension EFIconFontStrawberryIcon: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "StrawberryIcon-Free"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontStrawberryIcon: String {
    case about = "\u{e900}"
    case aboutL = "\u{e901}"
    case add = "\u{e902}"
    case airplane = "\u{e903}"
    case airplaneL = "\u{e904}"
    case alipay = "\u{e905}"
    case analysis = "\u{e906}"
    case android = "\u{e907}"
    case angleDownL = "\u{e908}"
    case angleLeftL = "\u{e909}"
    case angleRightL = "\u{e90a}"
    case angleUpL = "\u{e90b}"
    case apple = "\u{e90c}"
    case arrowDownL = "\u{e90d}"
    case arrowUpL = "\u{e90e}"
    case baiduwangpan = "\u{e90f}"
    case barChart = "\u{e910}"
    case barChartL = "\u{e911}"
    case battery = "\u{e912}"
    case batteryL = "\u{e913}"
    case bell = "\u{e914}"
    case bellL = "\u{e915}"
    case bevel = "\u{e916}"
    case bilibili = "\u{e917}"
    case bitcoin = "\u{e918}"
    case blackboard = "\u{e919}"
    case blackboardL = "\u{e91a}"
    case block = "\u{e91b}"
    case blockL = "\u{e91c}"
    case bluetooth = "\u{e91d}"
    case bluetoothL = "\u{e91e}"
    case board = "\u{e91f}"
    case boardL = "\u{e920}"
    case book = "\u{e921}"
    case bookL = "\u{e922}"
    case bookmark = "\u{e923}"
    case bookmarkL = "\u{e924}"
    case box = "\u{e925}"
    case boxL = "\u{e926}"
    case briefcase = "\u{e927}"
    case briefcaseL = "\u{e928}"
    case brush = "\u{e929}"
    case brushL = "\u{e92a}"
    case bug = "\u{e92b}"
    case bugL = "\u{e92c}"
    case building = "\u{e92d}"
    case buildingL = "\u{e92e}"
    case buy = "\u{e92f}"
    case buyL = "\u{e930}"
    case calculator = "\u{e931}"
    case calculatorL = "\u{e932}"
    case calendar = "\u{e933}"
    case calendarL = "\u{e934}"
    case camber = "\u{e935}"
    case camberL = "\u{e936}"
    case camberO = "\u{e937}"
    case camera = "\u{e938}"
    case cameraL = "\u{e939}"
    case categoryL = "\u{e93a}"
    case certificate = "\u{e93b}"
    case certificateL = "\u{e93c}"
    case chemistry = "\u{e93d}"
    case chemistryL = "\u{e93e}"
    case chooseListL = "\u{e93f}"
    case chrome = "\u{e940}"
    case circle = "\u{e941}"
    case circleL = "\u{e942}"
    case circleO = "\u{e943}"
    case clipL = "\u{e944}"
    case clock = "\u{e945}"
    case clockL = "\u{e946}"
    case closeL = "\u{e947}"
    case clothes = "\u{e948}"
    case clothesL = "\u{e949}"
    case cloud = "\u{e94a}"
    case cloudDownloadL = "\u{e94b}"
    case cloudL = "\u{e94c}"
    case cloudUploadL = "\u{e94d}"
    case codeBranch = "\u{e94e}"
    case codeFile = "\u{e94f}"
    case codeFileL = "\u{e950}"
    case codeFork = "\u{e951}"
    case codeL = "\u{e952}"
    case coin = "\u{e953}"
    case coinL = "\u{e954}"
    case collection = "\u{e955}"
    case comeL = "\u{e956}"
    case command = "\u{e957}"
    case commandL = "\u{e958}"
    case commed2 = "\u{e959}"
    case commed2L = "\u{e95a}"
    case comment = "\u{e95b}"
    case commentL = "\u{e95c}"
    case computer = "\u{e95d}"
    case computerL = "\u{e95e}"
    case configuration = "\u{e95f}"
    case configurationL = "\u{e960}"
    case control = "\u{e961}"
    case controlRank = "\u{e962}"
    case creditCard = "\u{e963}"
    case creditCardL = "\u{e964}"
    case crown = "\u{e965}"
    case crownL = "\u{e966}"
    case css3 = "\u{e967}"
    case cup = "\u{e968}"
    case cupL = "\u{e969}"
    case dashboard = "\u{e96a}"
    case dashboardL = "\u{e96b}"
    case diamond = "\u{e96c}"
    case diamondL = "\u{e96d}"
    case docEdit = "\u{e96e}"
    case docEditL = "\u{e96f}"
    case docFile = "\u{e970}"
    case docFileL = "\u{e971}"
    case downloadL = "\u{e972}"
    case dribbble = "\u{e973}"
    case dropbox = "\u{e974}"
    case earth = "\u{e975}"
    case earthL = "\u{e976}"
    case eye = "\u{e977}"
    case eyeL = "\u{e978}"
    case face = "\u{e979}"
    case facebook = "\u{e97a}"
    case faceL = "\u{e97b}"
    case file = "\u{e97c}"
    case fileL = "\u{e97d}"
    case film = "\u{e97e}"
    case filmL = "\u{e97f}"
    case fireL = "\u{e980}"
    case firewall = "\u{e981}"
    case firewallL = "\u{e982}"
    case folder = "\u{e983}"
    case folderL = "\u{e984}"
    case forum = "\u{e985}"
    case forumL = "\u{e986}"
    case game = "\u{e987}"
    case gameL = "\u{e988}"
    case gift = "\u{e989}"
    case giftL = "\u{e98a}"
    case github = "\u{e98b}"
    case githubLogo = "\u{e98c}"
    case Google = "\u{e98d}"
    case greatwall = "\u{e98e}"
    case hacker = "\u{e98f}"
    case hackerL = "\u{e990}"
    case hammer = "\u{e991}"
    case hammerL = "\u{e992}"
    case handBevel = "\u{e993}"
    case handButton = "\u{e994}"
    case handeVertical = "\u{e995}"
    case handGather = "\u{e996}"
    case handGrasp = "\u{e997}"
    case handHorizontal = "\u{e998}"
    case handPointer = "\u{e999}"
    case handSlide = "\u{e99a}"
    case handStop = "\u{e99b}"
    case handTouch = "\u{e99c}"
    case hdmi = "\u{e99d}"
    case hdmiL = "\u{e99e}"
    case headset = "\u{e99f}"
    case headsetL = "\u{e9a0}"
    case heart = "\u{e9a1}"
    case heartL = "\u{e9a2}"
    case home = "\u{e9a3}"
    case homeL = "\u{e9a4}"
    case html5 = "\u{e9a5}"
    case image = "\u{e9a6}"
    case imageL = "\u{e9a7}"
    case inbox = "\u{e9a8}"
    case inboxL = "\u{e9a9}"
    case Instagram = "\u{e9aa}"
    case key = "\u{e9ab}"
    case keyboard = "\u{e9ac}"
    case keyboardL = "\u{e9ad}"
    case keyL = "\u{e9ae}"
    case labelInfo = "\u{e9af}"
    case labelInfoL = "\u{e9b0}"
    case laptop = "\u{e9b1}"
    case laptopL = "\u{e9b2}"
    case layers = "\u{e9b3}"
    case layoutGrid = "\u{e9b4}"
    case layoutGrids = "\u{e9b5}"
    case layoutList = "\u{e9b6}"
    case light = "\u{e9b7}"
    case lightFlashL = "\u{e9b8}"
    case lightL = "\u{e9b9}"
    case lightning = "\u{e9ba}"
    case lightningL = "\u{e9bb}"
    case linkL = "\u{e9bc}"
    case linux = "\u{e9bd}"
    case listClipboard = "\u{e9be}"
    case listClipboardL = "\u{e9bf}"
    case location = "\u{e9c0}"
    case locationL = "\u{e9c1}"
    case lock = "\u{e9c2}"
    case lockL = "\u{e9c3}"
    case map = "\u{e9c4}"
    case mapL = "\u{e9c5}"
    case medal = "\u{e9c6}"
    case medalL = "\u{e9c7}"
    case menuL = "\u{e9c8}"
    case message = "\u{e9c9}"
    case messageL = "\u{e9ca}"
    case microchip = "\u{e9cb}"
    case microchipL = "\u{e9cc}"
    case microphone = "\u{e9cd}"
    case microphoneL = "\u{e9ce}"
    case microsoft = "\u{e9cf}"
    case mobile = "\u{e9d0}"
    case mobileL = "\u{e9d1}"
    case moments = "\u{e9d2}"
    case money = "\u{e9d3}"
    case moon = "\u{e9d4}"
    case moonL = "\u{e9d5}"
    case more = "\u{e9d6}"
    case mouse = "\u{e9d7}"
    case mouseL = "\u{e9d8}"
    case music = "\u{e9d9}"
    case musicFile = "\u{e9da}"
    case musicFileL = "\u{e9db}"
    case musicL = "\u{e9dc}"
    case musicNote = "\u{e9dd}"
    case musicNoteL = "\u{e9de}"
    case nail = "\u{e9df}"
    case nailL = "\u{e9e0}"
    case network = "\u{e9e1}"
    case networkL = "\u{e9e2}"
    case new = "\u{e9e3}"
    case newL = "\u{e9e4}"
    case newspaper = "\u{e9e5}"
    case newspaperL = "\u{e9e6}"
    case operation = "\u{e9e7}"
    case operationL = "\u{e9e8}"
    case outL = "\u{e9e9}"
    case pad = "\u{e9ea}"
    case padL = "\u{e9eb}"
    case paper = "\u{e9ec}"
    case paperL = "\u{e9ed}"
    case paperPlane = "\u{e9ee}"
    case paperPlaneL = "\u{e9ef}"
    case pauseL = "\u{e9f0}"
    case paypal = "\u{e9f1}"
    case pen = "\u{e9f2}"
    case penWrite = "\u{e9f3}"
    case people = "\u{e9f4}"
    case phone = "\u{e9f5}"
    case phoneL = "\u{e9f6}"
    case pinterest = "\u{e9f7}"
    case playL = "\u{e9f8}"
    case plugin = "\u{e9f9}"
    case pokemonBall = "\u{e9fa}"
    case port = "\u{e9fb}"
    case portL = "\u{e9fc}"
    case printer = "\u{e9fd}"
    case printerL = "\u{e9fe}"
    case product = "\u{e9ff}"
    case program = "\u{ea00}"
    case programL = "\u{ea01}"
    case qq = "\u{ea02}"
    case qrcodeL = "\u{ea03}"
    case quoteLeft = "\u{ea04}"
    case quoteRight = "\u{ea05}"
    case qzone = "\u{ea06}"
    case raspberry = "\u{ea07}"
    case raspberryL = "\u{ea08}"
    case read = "\u{ea09}"
    case readL = "\u{ea0a}"
    case redEnvelope = "\u{ea0b}"
    case renew = "\u{ea0c}"
    case rightClipboard = "\u{ea0d}"
    case rightClipboardL = "\u{ea0e}"
    case robot = "\u{ea0f}"
    case robot2 = "\u{ea10}"
    case robot2L = "\u{ea11}"
    case robotL = "\u{ea12}"
    case rocket = "\u{ea13}"
    case rocketL = "\u{ea14}"
    case rollerbrush = "\u{ea15}"
    case rollerbrushL = "\u{ea16}"
    case router = "\u{ea17}"
    case routerL = "\u{ea18}"
    case rss = "\u{ea19}"
    case ruler = "\u{ea1a}"
    case rulerL = "\u{ea1b}"
    case save = "\u{ea1c}"
    case saveL = "\u{ea1d}"
    case scanL = "\u{ea1e}"
    case scissors = "\u{ea1f}"
    case sdcard = "\u{ea20}"
    case sdcardL = "\u{ea21}"
    case searchL = "\u{ea22}"
    case server = "\u{ea23}"
    case serverL = "\u{ea24}"
    case servers = "\u{ea25}"
    case setting = "\u{ea26}"
    case settingL = "\u{ea27}"
    case share = "\u{ea28}"
    case shield = "\u{ea29}"
    case shieldL = "\u{ea2a}"
    case shop = "\u{ea2b}"
    case shopL = "\u{ea2c}"
    case shoppingCart = "\u{ea2d}"
    case shoppingCartL = "\u{ea2e}"
    case siteFolder = "\u{ea2f}"
    case siteFolderL = "\u{ea30}"
    case sliderL = "\u{ea31}"
    case square = "\u{ea32}"
    case squareL = "\u{ea33}"
    case squareO = "\u{ea34}"
    case star = "\u{ea35}"
    case starL = "\u{ea36}"
    case steam = "\u{ea37}"
    case storage = "\u{ea38}"
    case storageL = "\u{ea39}"
    case sun = "\u{ea3a}"
    case sunL = "\u{ea3b}"
    case sword = "\u{ea3c}"
    case swordL = "\u{ea3d}"
    case tab = "\u{ea3e}"
    case tabL = "\u{ea3f}"
    case tag = "\u{ea40}"
    case tagL = "\u{ea41}"
    case taiji = "\u{ea42}"
    case talk = "\u{ea43}"
    case talkL = "\u{ea44}"
    case taobao = "\u{ea45}"
    case telegram = "\u{ea46}"
    case textL = "\u{ea47}"
    case thumbsUp = "\u{ea48}"
    case thumbsUpL = "\u{ea49}"
    case ticket = "\u{ea4a}"
    case ticketL = "\u{ea4b}"
    case time = "\u{ea4c}"
    case timeL = "\u{ea4d}"
    case tmall = "\u{ea4e}"
    case transmissionL = "\u{ea4f}"
    case transport = "\u{ea50}"
    case trash = "\u{ea51}"
    case trashL = "\u{ea52}"
    case triangle = "\u{ea53}"
    case triangleL = "\u{ea54}"
    case triangleO = "\u{ea55}"
    case truck = "\u{ea56}"
    case truckL = "\u{ea57}"
    case tv = "\u{ea58}"
    case tvL = "\u{ea59}"
    case twitter = "\u{ea5a}"
    case uploadL = "\u{ea5b}"
    case usb = "\u{ea5c}"
    case usbL = "\u{ea5d}"
    case user = "\u{ea5e}"
    case userL = "\u{ea5f}"
    case v2ex = "\u{ea60}"
    case videoCamera = "\u{ea61}"
    case videoCameraL = "\u{ea62}"
    case videoFile = "\u{ea63}"
    case videoFileL = "\u{ea64}"
    case vimeo = "\u{ea65}"
    case volume = "\u{ea66}"
    case volumeL = "\u{ea67}"
    case volumeXL = "\u{ea68}"
    case warning = "\u{ea69}"
    case warningL = "\u{ea6a}"
    case watch = "\u{ea6b}"
    case watchL = "\u{ea6c}"
    case webcam = "\u{ea6d}"
    case webcamL = "\u{ea6e}"
    case webEdit = "\u{ea6f}"
    case webEditL = "\u{ea70}"
    case weibo = "\u{ea71}"
    case weixin = "\u{ea72}"
    case weixinzhifu = "\u{ea73}"
    case wifi = "\u{ea74}"
    case wordpress = "\u{ea75}"
    case wrench = "\u{ea76}"
    case wrenchL = "\u{ea77}"
    case writeL = "\u{ea78}"
    case xBuyL = "\u{ea79}"
    case youtube = "\u{ea7a}"
    case zhihu = "\u{ea7b}"
    case zipFolder = "\u{ea7c}"
    case zipFolderL = "\u{ea7d}"
}
