use_frameworks!

workspace 'Example'

project 'Example-iOS.xcodeproj'
project 'Example-tvOS.xcodeproj'
project 'Example-macOS.xcodeproj'

def shared_pods
  pod 'EFIconFont', :subspecs => ['Complete'], :path => '../'
end

target 'Example-iOS' do
  platform :ios, '9.0'
  project 'Example-iOS.xcodeproj'

  pod 'EFFoundation/Device', '1.4.9'
  shared_pods
end

target 'Example-tvOS' do
  platform :tvos, '9.0'
  project 'Example-tvOS.xcodeproj'
  
  pod 'EFFoundation', '1.4.9'
  shared_pods
end

target 'Example-macOS' do
  platform :osx, '10.12'
  project 'Example-macOS.xcodeproj'
  
  pod 'EFFoundation', '1.4.9'
  pod 'SnapKit', '5.0.1'
  shared_pods
end

target 'Example-watchOS' do
  platform :watchos, '2.0'
  project 'Example-iOS.xcodeproj'

  shared_pods
end
