//
//  EFIconFontAliCloudConsole.swift
//  EFIconFont
//
//  Created by EyreFree on 2021/6/28.
//
//  Copyright (c) 2021 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation
#if canImport(EFIconFontCore)
import EFIconFontCore
#endif

public extension EFIconFont {

    static let aliCloudConsole = EFIconFontAliCloudConsole.self
}

extension EFIconFontAliCloudConsole: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "alicloudconsole"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontAliCloudConsole: String {
    case account = "\u{e817}"
    case cog = "\u{e818}"
    case clock = "\u{e819}"
    case calendarAlt = "\u{e81a}"
    case cloudDownload = "\u{e81b}"
    case cloudUpload = "\u{e81c}"
    case exchange = "\u{e81d}"
    case infoCircle = "\u{e81e}"
    case questionCircle = "\u{e81f}"
    case exclamationCircle = "\u{e820}"
    case minusCircle = "\u{e821}"
    case plusCircle = "\u{e822}"
    case timesCircle = "\u{e823}"
    case checkCircle = "\u{e824}"
    case compressAlt = "\u{e825}"
    case expandAlt = "\u{e826}"
    case ban = "\u{e827}"
    case minus = "\u{e828}"
    case plus = "\u{e829}"
    case times = "\u{e82a}"
    case check = "\u{e82b}"
    case searchMinus = "\u{e82c}"
    case searchPlus = "\u{e82d}"
    case search = "\u{e82e}"
    case reply = "\u{e82f}"
    case undo = "\u{e830}"
    case redo = "\u{e831}"
    case externalLink = "\u{e832}"
    case arrowsAlt = "\u{e833}"
    case indent = "\u{e834}"
    case outdent = "\u{e835}"
    case sortLine = "\u{e836}"
    case `switch` = "\u{e837}"
    case windDescending = "\u{e838}"
    case windAscending = "\u{e839}"
    case download = "\u{e83a}"
    case upload = "\u{e83b}"
    case arrowToBottom = "\u{e83c}"
    case arrowToTop = "\u{e83d}"
    case longArrowDown = "\u{e83e}"
    case longArrowUp = "\u{e83f}"
    case arrowRight = "\u{e840}"
    case arrowLeft = "\u{e841}"
    case sort = "\u{e842}"
    case sortDown = "\u{e843}"
    case sortUp = "\u{e844}"
    case caretRight = "\u{e845}"
    case caretLeft = "\u{e846}"
    case arrowsV = "\u{e847}"
    case angleDoubleDown = "\u{e848}"
    case angleDoubleUp = "\u{e849}"
    case angleDoubleRight = "\u{e84a}"
    case angleDoubleLeft = "\u{e84b}"
    case angleDown = "\u{e84c}"
    case angleUp = "\u{e84d}"
    case angleRight = "\u{e84e}"
    case angleLeft = "\u{e84f}"
    case paperclip = "\u{e850}"
    case connection = "\u{e851}"
    case training = "\u{e853}"
    case process = "\u{e854}"
    case news = "\u{e855}"
    case save = "\u{e856}"
    case print = "\u{e857}"
    case newReleases = "\u{e858}"
    case release = "\u{e85a}"
    case alert = "\u{e85b}"
    case backspace = "\u{e85c}"
    case gem = "\u{e85d}"
    case integral = "\u{e85e}"
    case starCircle = "\u{e85f}"
    case userCircle = "\u{e860}"
    case cloudMachineFill = "\u{e861}"
    case cloudMachine = "\u{e862}"
    case terminalFill = "\u{e863}"
    case terminal = "\u{e864}"
    case shoppingCartFill = "\u{e865}"
    case resource = "\u{e867}"
    case rank = "\u{e86a}"
    case syncAlt = "\u{e86b}"
    case compass = "\u{e86c}"
    case arrowAltFromTop = "\u{e86d}"
    case arrowAltFromBotto = "\u{e86e}"
    case menu = "\u{e86f}"
    case iconDrag = "\u{e870}"
    case earlyWarning = "\u{e871}"
    case share = "\u{e872}"
    case share2 = "\u{e873}"
    case management = "\u{e874}"
    case accesskeys = "\u{e875}"
    case arrowSortDownSmall = "\u{e877}"
    case minusSquareFill = "\u{e878}"
    case plusSquareFill = "\u{e879}"
    case minusSquare = "\u{e87a}"
    case plusSquare = "\u{e87b}"
    case stepMode = "\u{e87d}"
    case scrollingMode = "\u{e87e}"
    case shoppingCart = "\u{e881}"
    case waitingFill = "\u{e882}"
    case waiting = "\u{e883}"
    case rightArrowRect = "\u{e884}"
    case leftArrowRect = "\u{e885}"
    case bell = "\u{e887}"
    case structuredData = "\u{e888}"
    case drag = "\u{e769}"
    case vector = "\u{e889}"
    case ellipsisV = "\u{e76a}"
    case NEW = "\u{e88a}"
    case galleryView = "\u{e76b}"
    case HOT = "\u{e88b}"
    case WIFI = "\u{e76c}"
    case home = "\u{e88c}"
    case bugReport = "\u{e76d}"
    case monitoring = "\u{e88e}"
    case qrcode = "\u{e76e}"
    case diagnose = "\u{e88f}"
    case scan = "\u{e76f}"
    case loading = "\u{e891}"
    case cut = "\u{e770}"
    case DirectoryTree = "\u{e892}"
    case gift = "\u{e771}"
    case application = "\u{e89e}"
    case link = "\u{e772}"
    case applicationGroup = "\u{e89f}"
    case poweroff = "\u{e774}"
    case key = "\u{e775}"
    case safetyCertificate = "\u{e776}"
    case supervise = "\u{e777}"
    case tagSubscipt = "\u{e78a}"
    case chartPieAlt = "\u{e78c}"
    case chartRelation = "\u{e78d}"
    case chartScatterPlot = "\u{e78e}"
    case chartArea = "\u{e78f}"
    case chartLine = "\u{e790}"
    case chartBar = "\u{e791}"
    case displayCode = "\u{e792}"
    case displayArrowRight = "\u{e793}"
    case displayArrowLeft = "\u{e794}"
    case laptopError = "\u{e795}"
    case laptopCheck = "\u{e796}"
    case laptop = "\u{e797}"
    case mobileError = "\u{e798}"
    case mobileCheck = "\u{e799}"
    case mobileAlt = "\u{e79a}"
    case aliwangwang = "\u{e79d}"
    case nail = "\u{e79e}"
    case nailFixed = "\u{e79f}"
    case edit = "\u{e7a0}"
    case dollar = "\u{e7a1}"
    case transanction = "\u{e7a2}"
    case filterFill = "\u{e7a3}"
    case allFill = "\u{e7a4}"
    case databasePlusFill = "\u{e7a5}"
    case databaseFill = "\u{e7a6}"
    case commentLinesFill = "\u{e7a7}"
    case commentDotsFill = "\u{e7a8}"
    case paperPlaneFill = "\u{e7a9}"
    case eyeSlashFill = "\u{e7aa}"
    case eyeFill = "\u{e7ab}"
    case lightbulbFill = "\u{e7ac}"
    case flagFill = "\u{e7ad}"
    case tagFill = "\u{e7ae}"
    case positionFill = "\u{e7af}"
    case locationFill = "\u{e7b0}"
    case mapFill = "\u{e7b1}"
    case inboxInFill = "\u{e7b2}"
    case boxFill = "\u{e7b3}"
    case databaseSetFill = "\u{e7b4}"
    case layerGroupFill = "\u{e7b5}"
    case cryFill = "\u{e7b6}"
    case smileFill = "\u{e7b7}"
    case unlockFill = "\u{e7b8}"
    case lockFill = "\u{e7b9}"
    case alignRightFill = "\u{e7ba}"
    case alignLeftFill = "\u{e7bb}"
    case borderBottomFill = "\u{e7bc}"
    case borderTopFill = "\u{e7bd}"
    case alignCenterFill = "\u{e7be}"
    case borderVerticleFill = "\u{e7bf}"
    case picCenterFill = "\u{e7c0}"
    case picSideFill = "\u{e7c1}"
    case folderOpenFill = "\u{e7c2}"
    case folderPlusFill = "\u{e7c3}"
    case folderFill = "\u{e7c4}"
    case fileSQL = "\u{e7c5}"
    case filePlusFill = "\u{e7c6}"
    case fileFill = "\u{e7c7}"
    case copyFill = "\u{e7c8}"
    case headsetFill = "\u{e7c9}"
    case phoneFill = "\u{e7ca}"
    case pauseCircleFill = "\u{e7cb}"
    case stopCircleFill = "\u{e7cc}"
    case playCircleFill = "\u{e7cd}"
    case deleteFill = "\u{e7ce}"
    case pictureFill = "\u{e7cf}"
    case mailFill = "\u{e7d0}"
    case heartFill = "\u{e7d1}"
    case collectionFill = "\u{e7d2}"
    case userGroupFill = "\u{e7d3}"
    case userPlusFill = "\u{e7d4}"
    case userFill = "\u{e7d5}"
    case cogFill = "\u{e7d6}"
    case clockFill = "\u{e7d7}"
    case calendarAltFill = "\u{e7d8}"
    case cloudDownloadFill = "\u{e7d9}"
    case cloudUploadFill = "\u{e7da}"
    case exchangeFill = "\u{e7db}"
    case infoCircleFill = "\u{e7dc}"
    case questionCircleFill = "\u{e7dd}"
    case exclamationCircleF = "\u{e7de}"
    case minusCircleFill = "\u{e7df}"
    case plusCircleFill = "\u{e7e0}"
    case timesCircleFill = "\u{e7e1}"
    case checkCircleFill = "\u{e7e2}"
    case compressAltFill = "\u{e7e3}"
    case expandAltFill = "\u{e7e4}"
    case filter = "\u{e7e5}"
    case all = "\u{e7e6}"
    case databasePlus = "\u{e7e7}"
    case database = "\u{e7e8}"
    case commentLines = "\u{e7e9}"
    case commentDots = "\u{e7ea}"
    case paperPlane = "\u{e7eb}"
    case eyeSlash = "\u{e7ec}"
    case eye = "\u{e7ed}"
    case lightbulb = "\u{e7ee}"
    case flag = "\u{e7ef}"
    case tag = "\u{e7f0}"
    case position = "\u{e7f1}"
    case location = "\u{e7f2}"
    case map = "\u{e7f3}"
    case inboxIn = "\u{e7f4}"
    case box = "\u{e7f5}"
    case databaseSet = "\u{e7f6}"
    case layerGroup = "\u{e7f7}"
    case windCry = "\u{e7f8}"
    case windSmile = "\u{e7f9}"
    case unlock = "\u{e7fa}"
    case lock = "\u{e7fb}"
    case alignRight = "\u{e7fc}"
    case alignLeft = "\u{e7fd}"
    case borderBottom = "\u{e7fe}"
    case borderTop = "\u{e7ff}"
    case alignCenter = "\u{e800}"
    case borderVerticle = "\u{e801}"
    case picCenter = "\u{e802}"
    case picSide = "\u{e803}"
    case folderOpen = "\u{e804}"
    case folderPlus = "\u{e805}"
    case folder = "\u{e806}"
    case fileSQL2 = "\u{e807}"
    case filePlus = "\u{e808}"
    case file = "\u{e809}"
    case copy = "\u{e80a}"
    case headset = "\u{e80b}"
    case phone = "\u{e80c}"
    case pauseCircle = "\u{e80d}"
    case stopCircle = "\u{e80e}"
    case playCircle = "\u{e80f}"
    case delete = "\u{e810}"
    case picture = "\u{e811}"
    case mail = "\u{e812}"
    case like = "\u{e813}"
    case collection = "\u{e814}"
    case userGroup = "\u{e815}"
    case accountPlus = "\u{e816}"
}
