//
//  EFIconFontFoundationIcons.swift
//  EFIconFont
//
//  Created by EyreFree on 2020/4/12.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation
#if canImport(Core)
import Core
#endif

public extension EFIconFont {

    static let foundationIcons = EFIconFontFoundationIcons.self
}

extension EFIconFontFoundationIcons: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "foundationicons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontFoundationIcons: String {
    case fiSocialDigg = "\u{ef34}"
    case fiSocialMedium = "\u{ef35}"
    case fiSocialWindows = "\u{ef36}"
    case fiSocialPicasa = "\u{ef37}"
    case fiTargetTwo = "\u{ef38}"
    case fiPrevious = "\u{ef39}"
    case fiMinus = "\u{ef3a}"
    case fiSocialDrive = "\u{ef3b}"
    case fiTrophy = "\u{ef3c}"
    case fiSocialYelp = "\u{ef3d}"
    case fiSocialSpotify = "\u{ef3e}"
    case fiSocialMyspace = "\u{ef3f}"
    case fiSocialJoomla = "\u{ef40}"
    case fiSubscript = "\u{ef41}"
    case fiSocialAdobe = "\u{ef42}"
    case fiSocialAndroid = "\u{ef43}"
    case fiVolume = "\u{ef44}"
    case fiRss = "\u{ef45}"
    case fiPageRemove = "\u{ef46}"
    case fiZoomOut = "\u{ef47}"
    case fiSocial500px = "\u{ef48}"
    case fiResultsDemographics = "\u{ef49}"
    case fiVolumeStrike = "\u{ef4a}"
    case fiListNumber = "\u{ef4b}"
    case fiSound = "\u{ef4c}"
    case fiSocialYahoo = "\u{ef4d}"
    case fiTabletLandscape = "\u{ef4e}"
    case fiSocialXbox = "\u{ef4f}"
    case fiSocialSteam = "\u{ef50}"
    case fiSocialSmashingMag = "\u{ef51}"
    case fiWheelchair = "\u{ef52}"
    case fiTorsoBusiness = "\u{ef53}"
    case fiSocialSquidoo = "\u{ef54}"
    case fiStrikethrough = "\u{ef55}"
    case fiTorsosMaleFemale = "\u{ef56}"
    case fiSocialFacebook = "\u{ef57}"
    case fiUpload = "\u{ef58}"
    case fiPause = "\u{ef59}"
    case fiSocialVimeo = "\u{ef5a}"
    case fiSocialStackOverflow = "\u{ef5b}"
    case fiPlayVideo = "\u{ef5c}"
    case fiSocialInstagram = "\u{ef5d}"
    case fiTrash = "\u{ef5e}"
    case fiSocialRdio = "\u{ef5f}"
    case fiStop = "\u{ef60}"
    case fiSocialForrst = "\u{ef61}"
    case fiTabletPortrait = "\u{ef62}"
    case fiStar = "\u{ef63}"
    case fiSocialTumblr = "\u{ef64}"
    case fiTelephoneAccessible = "\u{ef65}"
    case fiTorsosFemaleMale = "\u{ef66}"
    case fiSocialOrkut = "\u{ef67}"
    case fiSocialSkillshare = "\u{ef68}"
    case fiSocialSkype = "\u{ef69}"
    case fiUnderline = "\u{ef6a}"
    case fiSocialTwitter = "\u{ef6b}"
    case fiUniversalAccess = "\u{ef6c}"
    case fiSocialPinterest = "\u{ef6d}"
    case fiSocialHackerNews = "\u{ef6e}"
    case fiSocialYoutube = "\u{ef6f}"
    case fiTorsosAll = "\u{ef70}"
    case fiX = "\u{ef71}"
    case fiTrees = "\u{ef72}"
    case fiUsb = "\u{ef73}"
    case fiVideo = "\u{ef74}"
    case fiUnlink = "\u{ef75}"
    case fiWrench = "\u{ef76}"
    case fiSocialLinkedin = "\u{ef77}"
    case fiUploadCloud = "\u{ef78}"
    case fiAddressBook = "\u{ee79}"
    case fiTextColor = "\u{ef79}"
    case fiAlignRight = "\u{ee7a}"
    case fiVolumeNone = "\u{ef7a}"
    case fiAlignCenter = "\u{ee7b}"
    case fiSuperscript = "\u{ef7b}"
    case fiAlignLeft = "\u{ee7c}"
    case fiSocialBing = "\u{ef7c}"
    case fiAlert = "\u{ee7d}"
    case fiPrint = "\u{ef7d}"
    case fiAlignJustify = "\u{ee7e}"
    case fiTicket = "\u{ef7e}"
    case fiAnnotate = "\u{ee7f}"
    case fiProhibited = "\u{ef7f}"
    case fiArrowDown = "\u{ee80}"
    case fiYen = "\u{ef80}"
    case fiArrowLeft = "\u{ee81}"
    case fiWeb = "\u{ef81}"
    case fiArrowRight = "\u{ee82}"
    case fiSocialZurb = "\u{ef82}"
    case fiArrowsCompress = "\u{ee83}"
    case fiSocialGithub = "\u{ef83}"
    case fiArrowsExpand = "\u{ee84}"
    case fiSheriffBadge = "\u{ef84}"
    case fiArrowsIn = "\u{ee85}"
    case fiUnlock = "\u{ef85}"
    case fiArrowUp = "\u{ee86}"
    case fiSocialGooglePlus = "\u{ef86}"
    case fiAnchor = "\u{ee87}"
    case fiTorsoFemale = "\u{ef87}"
    case fiArchive = "\u{ee88}"
    case fiTorsosAllFemale = "\u{ef88}"
    case fiArrowsOut = "\u{ee89}"
    case fiSocialDribbble = "\u{ef89}"
    case fiAsl = "\u{ee8a}"
    case fiPricetagMultiple = "\u{ef8a}"
    case fiBatteryEmpty = "\u{ee8b}"
    case fiZoomIn = "\u{ef8b}"
    case fiBatteryFull = "\u{ee8c}"
    case fiSocialHi5 = "\u{ef8c}"
    case fiBold = "\u{ee8d}"
    case fiTorso = "\u{ef8d}"
    case fiAtSign = "\u{ee8e}"
    case fiSocialAmazon = "\u{ef8e}"
    case fiBlind = "\u{ee8f}"
    case fiXCircle = "\u{ef8f}"
    case fiAsterisk = "\u{ee90}"
    case fiSocialGameCenter = "\u{ef90}"
    case fiBitcoinCircle = "\u{ee91}"
    case fiWidget = "\u{ef91}"
    case fiBookmark = "\u{ee92}"
    case fiTorsos = "\u{ef92}"
    case fiBraille = "\u{ee93}"
    case fiSocialTreehouse = "\u{ef93}"
    case fiBook = "\u{ee94}"
    case fiBurst = "\u{ee95}"
    case fiCheckbox = "\u{ee96}"
    case fiCamera = "\u{ee97}"
    case fiBookBookmark = "\u{ee98}"
    case fiBackgroundColor = "\u{ee99}"
    case fiClock = "\u{ee9a}"
    case fiCss3 = "\u{ee9b}"
    case fiBluetooth = "\u{ee9c}"
    case fiCommentVideo = "\u{ee9d}"
    case fiClipboard = "\u{ee9e}"
    case fiBitcoin = "\u{ee9f}"
    case fiCalendar = "\u{eea0}"
    case fiCheck = "\u{eea1}"
    case fiBurstSale = "\u{eea2}"
    case fiCreditCard = "\u{eea3}"
    case fiCrop = "\u{eea4}"
    case fiCompass = "\u{eea5}"
    case fiBurstNew = "\u{eea6}"
    case fiDieFour = "\u{eea7}"
    case fiClosedCaption = "\u{eea8}"
    case fiClipboardPencil = "\u{eea9}"
    case fiComment = "\u{eeaa}"
    case fiDieTwo = "\u{eeab}"
    case fiCommentQuotes = "\u{eeac}"
    case fiCrown = "\u{eead}"
    case fiDieSix = "\u{eeae}"
    case fiDatabase = "\u{eeaf}"
    case fiCommentMinus = "\u{eeb0}"
    case fiFemaleSymbol = "\u{eeb1}"
    case fiContrast = "\u{eeb2}"
    case fiCloud = "\u{eeb3}"
    case fiBatteryHalf = "\u{eeb4}"
    case fiElevator = "\u{eeb5}"
    case fiEject = "\u{eeb6}"
    case fiDieFive = "\u{eeb7}"
    case fiDollarBill = "\u{eeb8}"
    case fiGraphBar = "\u{eeb9}"
    case fiHeart = "\u{eeba}"
    case fiFemale = "\u{eebb}"
    case fiGraphHorizontal = "\u{eebc}"
    case fiDislike = "\u{eebd}"
    case fiDieOne = "\u{eebe}"
    case fiGraphPie = "\u{eebf}"
    case fiHome = "\u{eec0}"
    case fiHtml5 = "\u{eec1}"
    case fiComments = "\u{eec2}"
    case fiFoot = "\u{eec3}"
    case fiMagnifyingGlass = "\u{eec4}"
    case fiFlag = "\u{eec5}"
    case fiFastForward = "\u{eec6}"
    case fiClipboardNotes = "\u{eec7}"
    case fiFolder = "\u{eec8}"
    case fiFirstAid = "\u{eec9}"
    case fiPageDelete = "\u{eeca}"
    case fiIndentMore = "\u{eecb}"
    case fiEye = "\u{eecc}"
    case fiListThumbnails = "\u{eecd}"
    case fiMobile = "\u{eece}"
    case fiKey = "\u{eecf}"
    case fiMaleFemale = "\u{eed0}"
    case fiDollar = "\u{eed1}"
    case fiFilter = "\u{eed2}"
    case fiList = "\u{eed3}"
    case fiMarker = "\u{eed4}"
    case fiPageDoc = "\u{eed5}"
    case fiIndentLess = "\u{eed6}"
    case fiFolderAdd = "\u{eed7}"
    case fiPageCsv = "\u{eed8}"
    case fiNoDogs = "\u{eed9}"
    case fiLock = "\u{eeda}"
    case fiInfo = "\u{eedb}"
    case fiMail = "\u{eedc}"
    case fiEuro = "\u{eedd}"
    case fiNext = "\u{eede}"
    case fiShare = "\u{eedf}"
    case fiLike = "\u{eee0}"
    case fiProjectionScreen = "\u{eee1}"
    case fiPageMultiple = "\u{eee2}"
    case fiHearingAid = "\u{eee3}"
    case fiPage = "\u{eee4}"
    case fiMonitor = "\u{eee5}"
    case fiNoSmoking = "\u{eee6}"
    case fiLaptop = "\u{eee7}"
    case fiRefresh = "\u{eee8}"
    case fiPageAdd = "\u{eee9}"
    case fiMinusCircle = "\u{eeea}"
    case fiPound = "\u{eeeb}"
    case fiDownload = "\u{eeec}"
    case fiPencil = "\u{eeed}"
    case fiFolderLock = "\u{eeee}"
    case fiMobileSignal = "\u{eeef}"
    case fiMicrophone = "\u{eef0}"
    case fiPlus = "\u{eef1}"
    case fiPhoto = "\u{eef2}"
    case fiPaintBucket = "\u{eef3}"
    case fiPageEdit = "\u{eef4}"
    case fiLightbulb = "\u{eef5}"
    case fiGraphTrend = "\u{eef6}"
    case fiPlayCircle = "\u{eef7}"
    case fiSocialFoursquare = "\u{eef8}"
    case fiItalic = "\u{eef9}"
    case fiMap = "\u{eefa}"
    case fiMaleSymbol = "\u{eefb}"
    case fiPageExportCsv = "\u{eefc}"
    case fiResults = "\u{eefd}"
    case fiPaw = "\u{eefe}"
    case fiLoop = "\u{eeff}"
    case fiPageExport = "\u{ef00}"
    case fiSocialBehance = "\u{ef01}"
    case fiPageFilled = "\u{ef02}"
    case fiSocialDropbox = "\u{ef03}"
    case fiDieThree = "\u{ef04}"
    case fiFoundation = "\u{ef05}"
    case fiPageCopy = "\u{ef06}"
    case fiGuideDog = "\u{ef07}"
    case fiPuzzle = "\u{ef08}"
    case fiRewindTen = "\u{ef09}"
    case fiPaperclip = "\u{ef0a}"
    case fiLayout = "\u{ef0b}"
    case fiSkull = "\u{ef0c}"
    case fiMusic = "\u{ef0d}"
    case fiPageExportPdf = "\u{ef0e}"
    case fiRewind = "\u{ef0f}"
    case fiPagePdf = "\u{ef10}"
    case fiSocialPath = "\u{ef11}"
    case fiPageSearch = "\u{ef12}"
    case fiPriceTag = "\u{ef13}"
    case fiRecord = "\u{ef14}"
    case fiShield = "\u{ef15}"
    case fiSocialApple = "\u{ef16}"
    case fiListBullet = "\u{ef17}"
    case fiSocialSnapchat = "\u{ef18}"
    case fiLink = "\u{ef19}"
    case fiSocialBlogger = "\u{ef1a}"
    case fiShuffle = "\u{ef1b}"
    case fiSave = "\u{ef1c}"
    case fiMale = "\u{ef1d}"
    case fiShoppingBag = "\u{ef1e}"
    case fiSocialDelicious = "\u{ef1f}"
    case fiQuote = "\u{ef20}"
    case fiPower = "\u{ef21}"
    case fiThumbnails = "\u{ef22}"
    case fiMegaphone = "\u{ef23}"
    case fiPlay = "\u{ef24}"
    case fiShoppingCart = "\u{ef25}"
    case fiTelephone = "\u{ef26}"
    case fiSocialStumbleupon = "\u{ef27}"
    case fiSocialDesignerNews = "\u{ef28}"
    case fiSocialEvernote = "\u{ef29}"
    case fiPageExportDoc = "\u{ef2a}"
    case fiSocialFlickr = "\u{ef2b}"
    case fiSocialDeviantArt = "\u{ef2c}"
    case fiSafetyCone = "\u{ef2d}"
    case fiSocialLastfm = "\u{ef2e}"
    case fiTarget = "\u{ef2f}"
    case fiSocialZerply = "\u{ef30}"
    case fiPaypal = "\u{ef31}"
    case fiMountains = "\u{ef32}"
    case fiSocialReddit = "\u{ef33}"
}
