//
//  EFIconFontDashicons.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    static let dashicons = EFIconFontDashicons.self
}

extension EFIconFontDashicons: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "dashicons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontDashicons: String {
    case update = "\u{ec2e}"
    case yes = "\u{ec2d}"
    case textPage = "\u{ec2c}"
    case videoAlt3 = "\u{ec2b}"
    case wordpress = "\u{ec2a}"
    case yesAlt = "\u{ec29}"
    case welcomeWidgetsMenus = "\u{ec28}"
    case wordpressAlt = "\u{ec27}"
    case welcomeViewSite = "\u{ec26}"
    case welcomeWriteBlog = "\u{ec25}"
    case welcomeComments = "\u{ec24}"
    case welcomeLearnMore = "\u{ec23}"
    case welcomeAddPage = "\u{ec22}"
    case visibility = "\u{ec21}"
    case updateAlt = "\u{ec20}"
    case videoAlt = "\u{ec1f}"
    case warning = "\u{ec1e}"
    case vault = "\u{ec1d}"
    case videoAlt2 = "\u{ec1c}"
    case upload = "\u{ec1b}"
    case universalAccess = "\u{ec1a}"
    case universalAccessAlt = "\u{ec19}"
    case trash = "\u{ec18}"
    case unlock = "\u{ec17}"
    case twitterAlt = "\u{ec16}"
    case translation = "\u{ec15}"
    case twitter = "\u{ec14}"
    case undo = "\u{ec13}"
    case tableRowBefore = "\u{ec12}"
    case tickets = "\u{ec11}"
    case ticketsAlt = "\u{ec10}"
    case tide = "\u{ec0f}"
    case thumbsUp = "\u{ec0e}"
    case text = "\u{ec0d}"
    case thumbsDown = "\u{ec0c}"
    case tagcloud = "\u{ec0b}"
    case testimonial = "\u{ec0a}"
    case smiley = "\u{ec09}"
    case tableRowDelete = "\u{ec08}"
    case tableColDelete = "\u{ec07}"
    case tag = "\u{ec06}"
    case tablet = "\u{ec05}"
    case tableRowAfter = "\u{ec04}"
    case tableColAfter = "\u{ec03}"
    case tableColBefore = "\u{ec02}"
    case starFilled = "\u{ec01}"
    case store = "\u{ec00}"
    case sticky = "\u{ebff}"
    case sort = "\u{ebfe}"
    case slides = "\u{ebfd}"
    case starHalf = "\u{ebfc}"
    case starEmpty = "\u{ebfb}"
    case shortcode = "\u{ebfa}"
    case sos = "\u{ebf9}"
    case schedule = "\u{ebf8}"
    case shareAlt = "\u{ebf7}"
    case smartphone = "\u{ebf6}"
    case search = "\u{ebf5}"
    case shield = "\u{ebf4}"
    case share = "\u{ebf3}"
    case shieldAlt = "\u{ebf2}"
    case editorTable = "\u{ebf1}"
    case shareAlt2 = "\u{ebf0}"
    case saved = "\u{ebef}"
    case remove = "\u{ebee}"
    case screenoptions = "\u{ebed}"
    case restApi = "\u{ebec}"
    case randomize = "\u{ebeb}"
    case products = "\u{ebea}"
    case rss = "\u{ebe9}"
    case redo = "\u{ebe8}"
    case plusAlt2 = "\u{ebe7}"
    case portfolio = "\u{ebe6}"
    case pressthis = "\u{ebe5}"
    case postStatus = "\u{ebe4}"
    case pluginsChecked = "\u{ebe3}"
    case plusAlt = "\u{ebe2}"
    case plus = "\u{ebe1}"
    case playlistVideo = "\u{ebe0}"
    case playlistAudio = "\u{ebdf}"
    case paperclip = "\u{ebde}"
    case performance = "\u{ebdd}"
    case palmtree = "\u{ebdc}"
    case phone = "\u{ebdb}"
    case no = "\u{ebda}"
    case nametag = "\u{ebd9}"
    case networking = "\u{ebd8}"
    case move = "\u{ebd7}"
    case noAlt = "\u{ebd6}"
    case minus = "\u{ebd5}"
    case migrate = "\u{ebd4}"
    case megaphone = "\u{ebd3}"
    case money = "\u{ebd2}"
    case menuAlt = "\u{ebd1}"
    case microphone = "\u{ebd0}"
    case mediaSpreadsheet = "\u{ebcf}"
    case mediaVideo = "\u{ebce}"
    case menu = "\u{ebcd}"
    case menuAlt3 = "\u{ebcc}"
    case mediaText = "\u{ebcb}"
    case menuAlt2 = "\u{ebca}"
    case mediaAudio = "\u{ebc9}"
    case formatAudio = "\u{ebc8}"
    case mediaArchive = "\u{ebc7}"
    case mediaDocument = "\u{ebc6}"
    case mediaInteractive = "\u{ebc5}"
    case mediaDefault = "\u{ebc4}"
    case lock = "\u{ebc3}"
    case mediaCode = "\u{ebc2}"
    case lockDuplicate = "\u{ebc1}"
    case marker = "\u{ebc0}"
    case location = "\u{ebbf}"
    case leftright = "\u{ebbe}"
    case locationAlt = "\u{ebbd}"
    case instagram = "\u{ebbc}"
    case lightbulb = "\u{ebbb}"
    case facebookAlt = "\u{ebba}"
    case listView = "\u{ebb9}"
    case insertAfter = "\u{ebb8}"
    case insert = "\u{ebb7}"
    case layout = "\u{ebb6}"
    case embedPhoto = "\u{ebb5}"
    case info = "\u{ebb4}"
    case laptop = "\u{ebb3}"
    case indexCard = "\u{ebb2}"
    case infoOutline = "\u{ebb1}"
    case insertBefore = "\u{ebb0}"
    case imageFlipVertical = "\u{ebaf}"
    case imagesAlt2 = "\u{ebae}"
    case imageRotateRight = "\u{ebad}"
    case imageRotate = "\u{ebac}"
    case imagesAlt = "\u{ebab}"
    case imageRotateLeft = "\u{ebaa}"
    case id = "\u{eba9}"
    case html = "\u{eba8}"
    case imageFlipHorizontal = "\u{eba7}"
    case idAlt = "\u{eba6}"
    case imageCrop = "\u{eba5}"
    case imageFilter = "\u{eba4}"
    case heading = "\u{eba3}"
    case hammer = "\u{eba2}"
    case hidden = "\u{eba1}"
    case gridView = "\u{eba0}"
    case heart = "\u{eb9f}"
    case formatVideo = "\u{eb9e}"
    case googleplus = "\u{eb9d}"
    case groups = "\u{eb9c}"
    case forms = "\u{eb9b}"
    case formatStatus = "\u{eb9a}"
    case formatImage = "\u{eb99}"
    case formatGallery = "\u{eb98}"
    case formatQuote = "\u{eb97}"
    case facebook = "\u{eb96}"
    case formatChat = "\u{eb95}"
    case formatAside = "\u{eb94}"
    case feedback = "\u{eb93}"
    case filter = "\u{eb92}"
    case flag = "\u{eb91}"
    case embedVideo = "\u{eb90}"
    case embedPost = "\u{eb8f}"
    case external = "\u{eb8e}"
    case editorVideo = "\u{eb8d}"
    case exit = "\u{eb8c}"
    case email = "\u{eb8b}"
    case excerptView = "\u{eb8a}"
    case embedGeneric = "\u{eb89}"
    case emailAlt = "\u{eb88}"
    case editorUl = "\u{eb87}"
    case editorUnderline = "\u{eb86}"
    case embedAudio = "\u{eb85}"
    case emailAlt2 = "\u{eb84}"
    case editorUnlink = "\u{eb83}"
    case editorPasteWord = "\u{eb82}"
    case ellipsis = "\u{eb81}"
    case editorStrikethrough = "\u{eb80}"
    case editorRtl = "\u{eb7f}"
    case editorTextcolor = "\u{eb7e}"
    case editorSpellcheck = "\u{eb7d}"
    case editorRemoveformatting = "\u{eb7c}"
    case editorLtr = "\u{eb7b}"
    case editorQuote = "\u{eb7a}"
    case editorPasteText = "\u{eb79}"
    case editorOl = "\u{eb78}"
    case editorOutdent = "\u{eb77}"
    case editorOlRtl = "\u{eb76}"
    case editorParagraph = "\u{eb75}"
    case editorKitchensink = "\u{eb74}"
    case editorItalic = "\u{eb73}"
    case editorHelp = "\u{eb72}"
    case editorJustify = "\u{eb71}"
    case editorContract = "\u{eb70}"
    case editorInsertmore = "\u{eb6f}"
    case editorIndent = "\u{eb6e}"
    case editorExpand = "\u{eb6d}"
    case adminLinks = "\u{eb6c}"
    case editorCustomchar = "\u{eb6b}"
    case editLarge = "\u{eb6a}"
    case editorCode = "\u{eb69}"
    case editorBold = "\u{eb68}"
    case editorCodeDuplicate = "\u{eb67}"
    case editorAlignleft = "\u{eb66}"
    case editorBreak = "\u{eb65}"
    case controlsSkipforward = "\u{eb64}"
    case controlsVolumeoff = "\u{eb63}"
    case dismiss = "\u{eb62}"
    case editorAlignright = "\u{eb61}"
    case editorAligncenter = "\u{eb60}"
    case desktop = "\u{eb5f}"
    case edit = "\u{eb5e}"
    case colorPicker = "\u{eb5d}"
    case download = "\u{eb5c}"
    case controlsVolumeon = "\u{eb5b}"
    case dashboard = "\u{eb5a}"
    case controlsSkipback = "\u{eb59}"
    case coverImage = "\u{eb58}"
    case buddiconsTopics = "\u{eb57}"
    case clipboard = "\u{eb56}"
    case controlsRepeat = "\u{eb55}"
    case columns = "\u{eb54}"
    case controlsForward = "\u{eb53}"
    case controlsPlay = "\u{eb52}"
    case controlsPause = "\u{eb51}"
    case codeStandards = "\u{eb50}"
    case chartArea = "\u{eb4f}"
    case cloudUpload = "\u{eb4e}"
    case cloud = "\u{eb4d}"
    case controlsBack = "\u{eb4c}"
    case chartLine = "\u{eb4b}"
    case clock = "\u{eb4a}"
    case cameraAlt = "\u{eb49}"
    case cloudSaved = "\u{eb48}"
    case chartBar = "\u{eb47}"
    case businessman = "\u{eb46}"
    case chartPie = "\u{eb45}"
    case cart = "\u{eb44}"
    case arrowRightAlt2 = "\u{eb43}"
    case camera = "\u{eb42}"
    case category = "\u{eb41}"
    case carrot = "\u{eb40}"
    case calendarAlt = "\u{eb3f}"
    case button = "\u{eb3e}"
    case calendar = "\u{eb3d}"
    case buddiconsTracking = "\u{eb3c}"
    case analytics = "\u{eb3b}"
    case businessperson = "\u{eb3a}"
    case buddiconsGroups = "\u{eb39}"
    case businesswoman = "\u{eb38}"
    case buddiconsPm = "\u{eb37}"
    case buddiconsReplies = "\u{eb36}"
    case building = "\u{eb35}"
    case buddiconsCommunity = "\u{eb34}"
    case buddiconsBbpressLogo = "\u{eb33}"
    case buddiconsForums = "\u{eb32}"
    case buddiconsFriends = "\u{eb31}"
    case buddiconsBuddypressLogo = "\u{eb30}"
    case buddiconsActivity = "\u{eb2f}"
    case bookAlt = "\u{eb2e}"
    case book = "\u{eb2d}"
    case awards = "\u{eb2c}"
    case arrowUpAlt2 = "\u{eb2b}"
    case blockDefault = "\u{eb2a}"
    case art = "\u{eb29}"
    case backup = "\u{eb28}"
    case arrowUpDuplicate = "\u{eb27}"
    case arrowUp = "\u{eb26}"
    case alignRight = "\u{eb25}"
    case arrowLeftAlt = "\u{eb24}"
    case arrowDown = "\u{eb23}"
    case arrowRight = "\u{eb22}"
    case arrowUpAlt = "\u{eb21}"
    case arrowLeftAlt2 = "\u{eb20}"
    case arrowLeft = "\u{eb1f}"
    case arrowRightAlt = "\u{eb1e}"
    case arrowDownAlt2 = "\u{eb1d}"
    case alignFullWidth = "\u{eb1c}"
    case album = "\u{eb1b}"
    case archive = "\u{eb1a}"
    case arrowDownAlt = "\u{eb19}"
    case alignCenter = "\u{eb18}"
    case alignWide = "\u{eb17}"
    case alignPullRight = "\u{eb16}"
    case adminSiteAlt2 = "\u{eb15}"
    case alignPullLeft = "\u{eb14}"
    case alignNone = "\u{eb13}"
    case adminTools = "\u{eb12}"
    case adminSite = "\u{eb11}"
    case adminUsers = "\u{eb10}"
    case alignLeft = "\u{eb0f}"
    case adminSiteAlt3 = "\u{eb0e}"
    case adminPost = "\u{eb0d}"
    case adminSiteAlt = "\u{eb0c}"
    case adminNetwork = "\u{eb0b}"
    case adminPlugins = "\u{eb0a}"
    case adminMultisite = "\u{eb09}"
    case adminSettings = "\u{eb08}"
    case adminPage = "\u{eb07}"
    case adminAppearance = "\u{eb06}"
    case adminMedia = "\u{eb05}"
    case adminHome = "\u{eb04}"
    case adminCustomizer = "\u{eb03}"
    case adminCollapse = "\u{eb02}"
    case adminGeneric = "\u{eb01}"
    case adminComments = "\u{eb00}"
}
