//
//  EFIconFontWeatherIcons.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    static let weatherIcons = EFIconFontWeatherIcons.self
}

extension EFIconFontWeatherIcons: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "weathericons"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontWeatherIcons: String {
    case wiSnowflakeCold = "\u{edd6}"
    case wiSnowWind = "\u{edd5}"
    case wiSnow = "\u{edd4}"
    case wiUmbrella = "\u{edd3}"
    case wiWindBeaufort11 = "\u{edd2}"
    case wiStormShowers = "\u{edd1}"
    case wiTornado = "\u{edd0}"
    case wiTsunami = "\u{edcf}"
    case wiWindBeaufort2 = "\u{edce}"
    case wiWindBeaufort3 = "\u{edcd}"
    case wiThermometerExterior = "\u{edcc}"
    case wiWindBeaufort4 = "\u{edcb}"
    case wiWindBeaufort5 = "\u{edca}"
    case wiTrain = "\u{edc9}"
    case wiWindBeaufort8 = "\u{edc8}"
    case wiTime10 = "\u{edc7}"
    case wiSprinkle = "\u{edc6}"
    case wiNightStormShowers = "\u{edc5}"
    case wiWindDeg = "\u{edc4}"
    case wiWindBeaufort12 = "\u{edc3}"
    case wiWindBeaufort0 = "\u{edc2}"
    case wiWindBeaufort10 = "\u{edc1}"
    case wiRefreshAlt = "\u{edc0}"
    case wiSolarEclipse = "\u{edbf}"
    case wiSleet = "\u{edbe}"
    case wiWindBeaufort9 = "\u{edbd}"
    case wiWindBeaufort1 = "\u{edbc}"
    case wiWindy = "\u{edbb}"
    case wiVolcano = "\u{edba}"
    case wiRainWind = "\u{edb9}"
    case wiThunderstorm = "\u{edb8}"
    case wiNightSnow = "\u{edb7}"
    case wiWindBeaufort7 = "\u{edb6}"
    case wiRainMix = "\u{edb5}"
    case wiWindBeaufort6 = "\u{edb4}"
    case wiTime7 = "\u{edb3}"
    case wiTime11 = "\u{edb2}"
    case wiTime12 = "\u{edb1}"
    case wiSmoke = "\u{edb0}"
    case wiShowers = "\u{edaf}"
    case wiStars = "\u{edae}"
    case wiTime8 = "\u{edad}"
    case wiSandstorm = "\u{edac}"
    case wiTime9 = "\u{edab}"
    case wiTime4 = "\u{edaa}"
    case wiTime6 = "\u{eda9}"
    case wiTime2 = "\u{eda8}"
    case wiTime1 = "\u{eda7}"
    case wiTime5 = "\u{eda6}"
    case wiNightSleet = "\u{eda5}"
    case wiNightSnowWind = "\u{eda4}"
    case wiNightSnowThunderstorm = "\u{eda3}"
    case wiTime3 = "\u{eda2}"
    case wiStrongWind = "\u{eda1}"
    case wiThermometerInternal = "\u{eda0}"
    case wiSunrise = "\u{ed9f}"
    case wiThermometer = "\u{ed9e}"
    case wiSunset = "\u{ed9d}"
    case wiNightSleetStorm = "\u{ed9c}"
    case wiSmog = "\u{ed9b}"
    case wiStormWarning = "\u{ed9a}"
    case wiNightRainMix = "\u{ed99}"
    case wiNightHail = "\u{ed98}"
    case wiNightRainWind = "\u{ed97}"
    case wiSmallCraftAdvisory = "\u{ed96}"
    case wiNightShowers = "\u{ed95}"
    case wiRaindrop = "\u{ed94}"
    case wiRefresh = "\u{ed93}"
    case wiRain = "\u{ed92}"
    case wiNightThunderstorm = "\u{ed91}"
    case wiNightSprinkle = "\u{ed90}"
    case wiRaindrops = "\u{ed8f}"
    case wiNightAltSnow = "\u{ed8e}"
    case wiNightAltThunderstorm = "\u{ed8d}"
    case wiNightAltSnowWind = "\u{ed8c}"
    case wiNightAltRainWind = "\u{ed8b}"
    case wiNightAltStormShowers = "\u{ed8a}"
    case wiNightAltSnowThunderstorm = "\u{ed89}"
    case wiNightRain = "\u{ed88}"
    case wiNightAltSleetStorm = "\u{ed87}"
    case wiNightAltSprinkle = "\u{ed86}"
    case wiNightAltRainMix = "\u{ed85}"
    case wiNightAltShowers = "\u{ed84}"
    case wiNightAltSleet = "\u{ed83}"
    case wiNightAltRain = "\u{ed82}"
    case wiNightAltHail = "\u{ed81}"
    case wiNightAltCloudyGusts = "\u{ed80}"
    case wiNightPartlyCloudy = "\u{ed7f}"
    case wiNightCloudyWindy = "\u{ed7e}"
    case wiNightLightning = "\u{ed7d}"
    case wiNightFog = "\u{ed7c}"
    case wiNightCloudyHigh = "\u{ed7b}"
    case wiNightCloudy = "\u{ed7a}"
    case wiNightClear = "\u{ed79}"
    case wiNightCloudyGusts = "\u{ed78}"
    case wiNightAltCloudy = "\u{ed77}"
    case wiMoonWaxingGibbous2 = "\u{ed76}"
    case wiNightAltPartlyCloudy = "\u{ed75}"
    case wiNightAltCloudyWindy = "\u{ed74}"
    case wiNightAltLightning = "\u{ed73}"
    case wiMoonset = "\u{ed72}"
    case wiMoonWaxingGibbous4 = "\u{ed71}"
    case wiMoonWaxingGibbous6 = "\u{ed70}"
    case wiNightAltCloudyHigh = "\u{ed6f}"
    case wiMoonWaxingGibbous3 = "\u{ed6e}"
    case wiMoonAltWaxingGibbous4 = "\u{ed6d}"
    case wiMoonWaxingGibbous5 = "\u{ed6c}"
    case wiMoonWaxingCrescent5 = "\u{ed6b}"
    case wiMoonWaxingCrescent3 = "\u{ed6a}"
    case wiMoonrise = "\u{ed69}"
    case wiNa = "\u{ed68}"
    case wiMoonWaxingCrescent6 = "\u{ed67}"
    case wiMoonWaningGibbous3 = "\u{ed66}"
    case wiMoonWaningCrescent4 = "\u{ed65}"
    case wiMoonWaxingCrescent4 = "\u{ed64}"
    case wiMoonWaxingCrescent2 = "\u{ed63}"
    case wiMoonWaxingGibbous1 = "\u{ed62}"
    case wiMoonWaningGibbous6 = "\u{ed61}"
    case wiMoonWaxingCrescent1 = "\u{ed60}"
    case wiMoonWaningGibbous5 = "\u{ed5f}"
    case wiMoonWaningCrescent5 = "\u{ed5e}"
    case wiMoonWaningGibbous1 = "\u{ed5d}"
    case wiMoonThirdQuarter = "\u{ed5c}"
    case wiMoonFull = "\u{ed5b}"
    case wiMoonWaningGibbous4 = "\u{ed5a}"
    case wiMoonWaningCrescent3 = "\u{ed59}"
    case wiMoonWaningCrescent6 = "\u{ed58}"
    case wiMoonWaningCrescent2 = "\u{ed57}"
    case wiMoonFirstQuarter = "\u{ed56}"
    case wiMoonWaningGibbous2 = "\u{ed55}"
    case wiMoonWaningCrescent1 = "\u{ed54}"
    case wiMoonNew = "\u{ed53}"
    case wiMoonAltWaxingGibbous6 = "\u{ed52}"
    case wiMoonAltWaxingGibbous5 = "\u{ed51}"
    case wiMoonAltWaxingGibbous3 = "\u{ed50}"
    case wiMoonAltWaxingCrescent3 = "\u{ed4f}"
    case wiMoonAltWaxingCrescent4 = "\u{ed4e}"
    case wiMoonAltWaxingGibbous2 = "\u{ed4d}"
    case wiMoonAltWaxingCrescent6 = "\u{ed4c}"
    case wiMoonAltWaxingGibbous1 = "\u{ed4b}"
    case wiMoonAltWaxingCrescent5 = "\u{ed4a}"
    case wiMoonAltWaningGibbous5 = "\u{ed49}"
    case wiMoonAltWaxingCrescent1 = "\u{ed48}"
    case wiMoonAltWaningCrescent2 = "\u{ed47}"
    case wiMoonAltWaningGibbous6 = "\u{ed46}"
    case wiMoonAltWaxingCrescent2 = "\u{ed45}"
    case wiMoonAltWaningCrescent6 = "\u{ed44}"
    case wiMoonAltWaningGibbous3 = "\u{ed43}"
    case wiMoonAltWaningGibbous4 = "\u{ed42}"
    case wiHorizon = "\u{ed41}"
    case wiHot = "\u{ed40}"
    case wiMoonAltWaningCrescent4 = "\u{ed3f}"
    case wiMoonAltWaningCrescent3 = "\u{ed3e}"
    case wiMoonAltWaningGibbous1 = "\u{ed3d}"
    case wiMoonAltWaningGibbous2 = "\u{ed3c}"
    case wiMoonAltWaningCrescent5 = "\u{ed3b}"
    case wiMoonAltWaningCrescent1 = "\u{ed3a}"
    case wiMoonAltThirdQuarter = "\u{ed39}"
    case wiMeteor = "\u{ed38}"
    case wiMoonAltFull = "\u{ed37}"
    case wiMoonAltNew = "\u{ed36}"
    case wiMoonAltFirstQuarter = "\u{ed35}"
    case wiHurricane = "\u{ed34}"
    case wiHurricaneWarning = "\u{ed33}"
    case wiLunarEclipse = "\u{ed32}"
    case wiLightning = "\u{ed31}"
    case wiHorizonAlt = "\u{ed30}"
    case wiHumidity = "\u{ed2f}"
    case wiFire = "\u{ed2e}"
    case wiHail = "\u{ed2d}"
    case wiGaleWarning = "\u{ed2c}"
    case wiFog = "\u{ed2b}"
    case wiDirectionUpRight = "\u{ed2a}"
    case wiFlood = "\u{ed29}"
    case wiFahrenheit = "\u{ed28}"
    case wiDust = "\u{ed27}"
    case wiDirectionRight = "\u{ed26}"
    case wiEarthquake = "\u{ed25}"
    case wiDirectionUpLeft = "\u{ed24}"
    case wiDayThunderstorm = "\u{ed23}"
    case wiDayWindy = "\u{ed22}"
    case wiDirectionUp = "\u{ed21}"
    case wiDirectionDownLeft = "\u{ed20}"
    case wiDirectionDown = "\u{ed1f}"
    case wiDirectionLeft = "\u{ed1e}"
    case wiDaySunny = "\u{ed1d}"
    case wiDirectionDownRight = "\u{ed1c}"
    case wiDegrees = "\u{ed1b}"
    case wiDaySunnyOvercast = "\u{ed1a}"
    case wiDaySprinkle = "\u{ed19}"
    case wiDaySleet = "\u{ed18}"
    case wiDayStormShowers = "\u{ed17}"
    case wiDaySnowThunderstorm = "\u{ed16}"
    case wiDaySnow = "\u{ed15}"
    case wiDayShowers = "\u{ed14}"
    case wiDayRainMix = "\u{ed13}"
    case wiDaySnowWind = "\u{ed12}"
    case wiDayRain = "\u{ed11}"
    case wiDaySleetStorm = "\u{ed10}"
    case wiDayLightning = "\u{ed0f}"
    case wiDayHaze = "\u{ed0e}"
    case wiDayCloudy = "\u{ed0d}"
    case wiDayRainWind = "\u{ed0c}"
    case wiDayHail = "\u{ed0b}"
    case wiDayLightWind = "\u{ed0a}"
    case wiDayCloudyWindy = "\u{ed09}"
    case wiCloudyGusts = "\u{ed08}"
    case wiDayCloudyGusts = "\u{ed07}"
    case wiDayFog = "\u{ed06}"
    case wiDayCloudyHigh = "\u{ed05}"
    case wiCloudy = "\u{ed04}"
    case wiCloudRefresh = "\u{ed03}"
    case wiCloud = "\u{ed02}"
    case wiCloudyWindy = "\u{ed01}"
    case wiCloudUp = "\u{ed00}"
    case wiCloudDown = "\u{ecff}"
    case wiBarometer = "\u{ecfe}"
    case wiCelsius = "\u{ecfd}"
    case wiAlien = "\u{ecfc}"
}
