//
//  EFIconFontStroke7.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation
#if canImport(EFIconFontCore)
import EFIconFontCore
#endif

public extension EFIconFont {

    static let stroke7 = EFIconFontStroke7.self
}

extension EFIconFontStroke7: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "stroke7"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontStroke7: String {
    case usb = "\u{ed6d}"
    case wine = "\u{ed6c}"
    case unlock = "\u{ed6b}"
    case volume = "\u{ed6a}"
    case `switch` = "\u{ed69}"
    case volume2 = "\u{ed68}"
    case userFemale = "\u{ed67}"
    case upArrow = "\u{ed66}"
    case users = "\u{ed65}"
    case medal = "\u{ed64}"
    case ribbon = "\u{ed63}"
    case ticket = "\u{ed62}"
    case science = "\u{ed61}"
    case server = "\u{ed60}"
    case wallet = "\u{ed5f}"
    case tools = "\u{ed5e}"
    case world = "\u{ed5d}"
    case trash = "\u{ed5c}"
    case signal = "\u{ed5b}"
    case umbrella = "\u{ed5a}"
    case shuffle = "\u{ed59}"
    case way = "\u{ed58}"
    case target = "\u{ed57}"
    case search = "\u{ed56}"
    case vector = "\u{ed55}"
    case plugin = "\u{ed54}"
    case network = "\u{ed53}"
    case star = "\u{ed52}"
    case smile = "\u{ed51}"
    case wristwatch = "\u{ed50}"
    case shield = "\u{ed4f}"
    case share = "\u{ed4e}"
    case speaker = "\u{ed4d}"
    case safe = "\u{ed4c}"
    case study = "\u{ed4b}"
    case voicemail = "\u{ed4a}"
    case pin = "\u{ed49}"
    case volume1 = "\u{ed48}"
    case video = "\u{ed47}"
    case settings = "\u{ed46}"
    case paint = "\u{ed45}"
    case magnet = "\u{ed44}"
    case user = "\u{ed43}"
    case refreshCloud = "\u{ed42}"
    case photoGallery = "\u{ed41}"
    case upload = "\u{ed40}"
    case stopwatch = "\u{ed3f}"
    case sun = "\u{ed3e}"
    case timer = "\u{ed3d}"
    case graph = "\u{ed3c}"
    case print = "\u{ed3b}"
    case scissors = "\u{ed3a}"
    case newsPaper = "\u{ed39}"
    case menu = "\u{ed38}"
    case refresh2 = "\u{ed37}"
    case rightArrow = "\u{ed36}"
    case refresh = "\u{ed35}"
    case plane = "\u{ed34}"
    case pendrive = "\u{ed33}"
    case shopbag = "\u{ed32}"
    case power = "\u{ed31}"
    case plug = "\u{ed30}"
    case pen = "\u{ed2f}"
    case mute = "\u{ed2e}"
    case radio = "\u{ed2d}"
    case map2 = "\u{ed2c}"
    case headphones = "\u{ed2b}"
    case mail = "\u{ed2a}"
    case rocket = "\u{ed29}"
    case `repeat` = "\u{ed28}"
    case prev = "\u{ed27}"
    case photo = "\u{ed26}"
    case paintBucket = "\u{ed25}"
    case next = "\u{ed24}"
    case plus = "\u{ed23}"
    case moon = "\u{ed22}"
    case piggy = "\u{ed21}"
    case portfolio = "\u{ed20}"
    case mapMarker = "\u{ed1f}"
    case music = "\u{ed1e}"
    case notebook = "\u{ed1d}"
    case keypad = "\u{ed1c}"
    case play = "\u{ed1b}"
    case mouse = "\u{ed1a}"
    case phone = "\u{ed19}"
    case musiclist = "\u{ed18}"
    case more = "\u{ed17}"
    case note2 = "\u{ed16}"
    case paperPlane = "\u{ed15}"
    case paperclip = "\u{ed14}"
    case next2 = "\u{ed13}"
    case light = "\u{ed12}"
    case look = "\u{ed11}"
    case magicWand = "\u{ed10}"
    case note = "\u{ed0f}"
    case mailOpen = "\u{ed0e}"
    case less = "\u{ed0d}"
    case disk = "\u{ed0c}"
    case exapnd2 = "\u{ed0b}"
    case micro = "\u{ed0a}"
    case monitor = "\u{ed09}"
    case help1 = "\u{ed08}"
    case lock = "\u{ed07}"
    case help2 = "\u{ed06}"
    case male = "\u{ed05}"
    case loop = "\u{ed04}"
    case map = "\u{ed03}"
    case mailOpenFile = "\u{ed02}"
    case link = "\u{ed01}"
    case leaf = "\u{ed00}"
    case lintern = "\u{ecff}"
    case like2 = "\u{ecfe}"
    case joy = "\u{ecfd}"
    case id = "\u{ecfc}"
    case junk = "\u{ecfb}"
    case leftArrow = "\u{ecfa}"
    case hourglass = "\u{ecf9}"
    case key = "\u{ecf8}"
    case like = "\u{ecf7}"
    case info = "\u{ecf6}"
    case global = "\u{ecf5}"
    case gift = "\u{ecf4}"
    case drop = "\u{ecf3}"
    case glasses = "\u{ecf2}"
    case hammer = "\u{ecf1}"
    case helm = "\u{ecf0}"
    case graph3 = "\u{ecef}"
    case graph1 = "\u{ecee}"
    case female = "\u{eced}"
    case flag = "\u{ecec}"
    case gym = "\u{eceb}"
    case graph2 = "\u{ecea}"
    case home = "\u{ece9}"
    case deleteUser = "\u{ece8}"
    case display2 = "\u{ece7}"
    case file = "\u{ece6}"
    case edit = "\u{ece5}"
    case cloudUpload = "\u{ece4}"
    case gleam = "\u{ece3}"
    case expand1 = "\u{ece2}"
    case filter = "\u{ece1}"
    case film = "\u{ece0}"
    case config = "\u{ecdf}"
    case download = "\u{ecde}"
    case date = "\u{ecdd}"
    case folder = "\u{ecdc}"
    case eyedropper = "\u{ecdb}"
    case diskette = "\u{ecda}"
    case display1 = "\u{ecd9}"
    case drawer = "\u{ecd8}"
    case copyFile = "\u{ecd7}"
    case camera = "\u{ecd6}"
    case browser = "\u{ecd5}"
    case crop = "\u{ecd4}"
    case arc = "\u{ecd3}"
    case comment = "\u{ecd2}"
    case doorLock = "\u{ecd1}"
    case check = "\u{ecd0}"
    case cash = "\u{eccf}"
    case culture = "\u{ecce}"
    case call = "\u{eccd}"
    case cup = "\u{eccc}"
    case cloudDownload = "\u{eccb}"
    case calculator = "\u{ecca}"
    case coffee = "\u{ecc9}"
    case diamond = "\u{ecc8}"
    case car = "\u{ecc7}"
    case closeCircle = "\u{ecc6}"
    case credit = "\u{ecc5}"
    case bandaid = "\u{ecc4}"
    case bicycle = "\u{ecc3}"
    case clock = "\u{ecc2}"
    case cloud = "\u{ecc1}"
    case compass = "\u{ecc0}"
    case chat = "\u{ecbf}"
    case angleLeftCircle = "\u{ecbe}"
    case box1 = "\u{ecbd}"
    case bookmarks = "\u{ecbc}"
    case bottomArrow = "\u{ecbb}"
    case cart = "\u{ecba}"
    case close = "\u{ecb9}"
    case angleUp = "\u{ecb8}"
    case back = "\u{ecb7}"
    case bluetooth = "\u{ecb6}"
    case angleUpCircle = "\u{ecb5}"
    case battery = "\u{ecb4}"
    case box2 = "\u{ecb3}"
    case angleRightCircle = "\u{ecb2}"
    case addUser = "\u{ecb1}"
    case angleRight = "\u{ecb0}"
    case back2 = "\u{ecaf}"
    case bell = "\u{ecae}"
    case ball = "\u{ecad}"
    case alarm = "\u{ecac}"
    case airplay = "\u{ecab}"
    case angleLeft = "\u{ecaa}"
    case angleDown = "\u{eca9}"
    case attention = "\u{eca8}"
    case anchor = "\u{eca7}"
    case albums = "\u{eca6}"
    case angleDownCircle = "\u{eca5}"
    case album = "\u{eca4}"
}
