//
//  EFIconFontLigatureSymbols.swift
//  EFIconFont
//
//  Created by EyreFree on 2019/3/20.
//
//  Copyright (c) 2019 EyreFree <eyrefree@eyrefree.org>
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.

import Foundation

public extension EFIconFont {

    static let ligatureSymbols = EFIconFontLigatureSymbols.self
}

extension EFIconFontLigatureSymbols: EFIconFontCaseIterableProtocol {

    public static var name: String {
        return "LigatureSymbols"
    }

    public var unicode: String {
        return self.rawValue
    }
}

public enum EFIconFontLigatureSymbols: String {
    case table = "\u{E127}"
    case copy = "\u{E038}"
    case cut = "\u{E03b}"
    case backspace = "\u{E010}"
    case alignleft = "\u{E005}"
    case aligncenter = "\u{E004}"
    case alignright = "\u{E006}"
    case alignadjust = "\u{E003}"
    case italic = "\u{E079}"
    case bold = "\u{E01f}"
    case underline = "\u{E132}"
    case strike = "\u{E159}"
    case emphasis = "\u{E152}"
    case code = "\u{E032}"
    case link = "\u{E082}"
    case quote = "\u{E10b}"
    case graph = "\u{E05b}"
    case magic = "\u{E089}"
    case brush = "\u{E022}"
    case color = "\u{E033}"
    case contrast = "\u{E001}"
    case ink = "\u{E14a}"
    case gradation = "\u{E149}"
    case sepia = "\u{E14e}"
    case invert = "\u{E14b}"
    case paint = "\u{E09b}"
    case paramater = "\u{E09c}"
    case crop = "\u{E039}"
    case check = "\u{E029}"
    case checkbox = "\u{E02a}"
    case checkboxempty = "\u{E02b}"
    case pc = "\u{E09e}"
    case keyboard = "\u{E07d}"
    case mobile = "\u{E078}"
    case horizontal = "\u{E071}"
    case vertical = "\u{E138}"
    case web = "\u{E13f}"
    case mail = "\u{E08a}"
    case shopping = "\u{E119}"
    case dashboard = "\u{E03c}"
    case key = "\u{E07c}"
    case sns = "\u{E11f}"
    case calendar = "\u{E15e}"
    case dailycalendar = "\u{E025}"
    case ban = "\u{E012}"
    case remove = "\u{E10f}"
    case pen = "\u{E09f}"
    case eraser = "\u{E148}"
    case edit = "\u{E041}"
    case tabs = "\u{E095}"
    case tag = "\u{E128}"
    case setup = "\u{E117}"
    case setting = "\u{E055}"
    case etc = "\u{E043}"
    case clip = "\u{E030}"
    case bookmark = "\u{E021}"
    case book = "\u{E020}"
    case album = "\u{E002}"
    case user = "\u{E137}"
    case friend = "\u{E051}"
    case group = "\u{E05c}"
    case frustrate = "\u{E052}"
    case laugh = "\u{E07f}"
    case wink = "\u{E081}"
    case smile = "\u{E11e}"
    case surprise = "\u{E124}"
    case trouble = "\u{E12d}"
    case male = "\u{E176}"
    case female = "\u{E175}"
    case game = "\u{E054}"
    case globe = "\u{E058}"
    case home = "\u{E072}"
    case building = "\u{E023}"
    case rss = "\u{E113}"
    case server = "\u{E16c}"
    case sitemap = "\u{E16d}"
    case app = "\u{E009}"
    case memo = "\u{E08d}"
    case meal = "\u{E08c}"
    case coffee = "\u{E146}"
    case spa = "\u{E177}"
    case college = "\u{E174}"
    case bag = "\u{E173}"
    case present = "\u{E109}"
    case umbrella = "\u{E178}"
    case twinkle = "\u{E073}"
    case crown = "\u{E03a}"
    case category = "\u{E028}"
    case circle = "\u{E02e}"
    case info = "\u{E075}"
    case help = "\u{E070}"
    case refreshbutton = "\u{E14d}"
    case terminal = "\u{E16e}"
    case file = "\u{E048}"
    case print = "\u{E10a}"
    case delete = "\u{E12c}"
    case clear = "\u{E02f}"
    case save = "\u{E115}"
    case upload = "\u{E136}"
    case cloud = "\u{E031}"
    case folder = "\u{E04c}"
    case camera = "\u{E026}"
    case photo = "\u{E101}"
    case image = "\u{E074}"
    case barcode = "\u{E013}"
    case phone = "\u{E100}"
    case music = "\u{E094}"
    case video = "\u{E139}"
    case playmedia = "\u{E107}"
    case record = "\u{E10d}"
    case play = "\u{E106}"
    case pause = "\u{E09d}"
    case stop = "\u{E123}"
    case eject = "\u{E042}"
    case bell = "\u{E014}"
    case volumeup = "\u{E13d}"
    case volumedown = "\u{E13c}"
    case volume = "\u{E13b}"
    case off = "\u{E098}"
    case light = "\u{E14c}"
    case dark = "\u{E147}"
    case lock = "\u{E086}"
    case unlock = "\u{E134}"
    case flag = "\u{E04a}"
    case wifi = "\u{E140}"
    case time = "\u{E12b}"
    case map = "\u{E08b}"
    case geo = "\u{E056}"
    case location = "\u{E085}"
    case pin = "\u{E103}"
    case walking = "\u{E13e}"
    case bicycle = "\u{E015}"
    case car = "\u{E027}"
    case bus = "\u{E024}"
    case plane = "\u{E105}"
    case compass = "\u{E036}"
    case cursor = "\u{E166}"
    case pointer = "\u{E16b}"
    case grab = "\u{E169}"
    case arrowup = "\u{E00e}"
    case arrowright = "\u{E00d}"
    case arrowdown = "\u{E00b}"
    case arrowleft = "\u{E00c}"
    case up = "\u{E135}"
    case right = "\u{E112}"
    case down = "\u{E03e}"
    case left = "\u{E080}"
    case back = "\u{E00f}"
    case next = "\u{E096}"
    case dropdown = "\u{E040}"
    case sort = "\u{E120}"
    case good = "\u{E059}"
    case bad = "\u{E011}"
    case full = "\u{E053}"
    case small = "\u{E11d}"
    case move = "\u{E093}"
    case undo = "\u{E133}"
    case forward = "\u{E04e}"
    case reply = "\u{E111}"
    case share = "\u{E118}"
    case login = "\u{E087}"
    case logout = "\u{E088}"
    case exchange = "\u{E045}"
    case shuffle = "\u{E11a}"
    case `repeat` = "\u{E110}"
    case refresh = "\u{E10e}"
    case sync = "\u{E125}"
    case external = "\u{E046}"
    case addstar = "\u{E000}"
    case star = "\u{E121}"
    case starempty = "\u{E122}"
    case heart = "\u{E06e}"
    case heartempty = "\u{E06f}"
    case view = "\u{E13a}"
    case comment = "\u{E034}"
    case comments = "\u{E035}"
    case plus = "\u{E108}"
    case minus = "\u{E08f}"
    case zoomin = "\u{E142}"
    case zoomout = "\u{E143}"
    case search = "\u{E116}"
    case menu = "\u{E08e}"
    case tilemenu = "\u{E12a}"
    case list = "\u{E084}"
    case tile = "\u{E129}"
    case notify = "\u{E097}"
    case apple = "\u{E00a}"
    case android = "\u{E008}"
    case windows = "\u{E151}"
    case ubuntu = "\u{E17b}"
    case amazon = "\u{E007}"
    case facebook = "\u{E047}"
    case twitter = "\u{E12f}"
    case vk = "\u{E17c}"
    case google = "\u{E05a}"
    case yahoo = "\u{E172}"
    case bing = "\u{E164}"
    case hatena = "\u{E05d}"
    case hatenabookmark = "\u{E161}"
    case digg = "\u{E167}"
    case linkedin = "\u{E083}"
    case myspace = "\u{E16a}"
    case paperboy = "\u{E162}"
    case mixi = "\u{E090}"
    case line = "\u{E157}"
    case mobage = "\u{E158}"
    case gree = "\u{E153}"
    case skype = "\u{E11b}"
    case aim = "\u{E163}"
    case yelp = "\u{E17d}"
    case foursquare = "\u{E04d}"
    case pinterest = "\u{E104}"
    case flickr = "\u{E04b}"
    case tumblr = "\u{E12e}"
    case wordpress = "\u{E171}"
    case blogger = "\u{E165}"
    case evernote = "\u{E044}"
    case dropbox = "\u{E168}"
    case slideshare = "\u{E179}"
    case github = "\u{E057}"
    case yapcasialogomark = "\u{E15c}"
    case dribbble = "\u{E03f}"
    case cookpad = "\u{E037}"
    case instapaper = "\u{E076}"
    case readability = "\u{E10c}"
    case gumroad = "\u{E154}"
    case picasa = "\u{E102}"
    case instagram = "\u{E155}"
    case delicious = "\u{E03d}"
    case youtube = "\u{E141}"
    case vimeo = "\u{E170}"
    case ustream = "\u{E16f}"
    case soundcloud = "\u{E17a}"
    case chrome = "\u{E02c}"
    case safari = "\u{E114}"
    case sleipnir = "\u{E11c}"
    case firefox = "\u{E049}"
    case opera = "\u{E099}"
    case internetexplorer = "\u{E077}"
}
