name: deploy

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  deploy:
    runs-on: macos-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh

      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA_1: ${{ secrets.PROVISIONING_PROFILE_DATA_1 }}
          PROVISIONING_PROFILE_DATA_2: ${{ secrets.PROVISIONING_PROFILE_DATA_2 }}
          PROVISIONING_PROFILE_DATA_3: ${{ secrets.PROVISIONING_PROFILE_DATA_3 }}
        run: |
          exec .github/scripts/import-profile.sh

      - name: Dependency
        run: |
          sh Startup.sh

      - name: Build app
        run: |
          fastlane build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: ~/Library/Logs/gym/*.log

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PRODUCT_NAME }}.ipa
            ${{ env.PRODUCT_NAME }}.app.dSYM.zip
        env:
          GITHUB_TOKEN: ${{ secrets.EF_GITHUB_TOKEN }}

      - name: Upload app to App Store Connect
        if: |
          startsWith(github.ref, 'refs/tags/v') ||
          startsWith(github.event.head_commit.message, 'testflight')
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f "$PRODUCT_NAME.ipa" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"
